const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const productDir = path.join(__dirname, '../product');
const html = fs.readFileSync(path.join(productDir, 'index.html'), 'utf8');
assert.doesNotMatch(html, /download-checks|app-capture|data-showcase-try/);
assert.doesNotMatch(html, /<section[^>]+id="updates"|class="updates-history"|class="milestone-update"/);
assert.ok(html.includes('href="../updates/" target="_blank" rel="noopener">更新日志'));
const arm64 = [...html.matchAll(/data-download-arch="arm64"[^>]*href="([^"]+)"/g)];
assert.equal(arm64.length, 4);
assert.ok(arm64.every(m => /\/v0\.4\.3\/Qiuqiu-0\.4\.03-macOS-arm64(?:-share\.zip|\.dmg)$/.test(m[1])));
assert.match(html, /<dt>版本<\/dt><dd>0\.4\.03<\/dd>/);
const updates = fs.readFileSync(path.join(productDir, '../updates/index.html'), 'utf8');
const releaseDate = updates.match(/id="v0\.4\.03-apple"[\s\S]*?<time datetime="(\d{4}-\d{2}-\d{2})"/)[1];
assert.ok(html.includes(`<dt>发布日期</dt><dd>${releaseDate}</dd>`));
assert.match(html, /直接选择本机 Codex 自定义宠物/);
assert.match(html, /9 类动作/);
assert.match(html, /保存后应用到桌面，并同步聊天头像/);
const demoTitles = [...html.matchAll(/<iframe[^>]+title="([^"]+)"/g)].map(m => m[1]);
assert.equal(demoTitles.filter(title => title.startsWith('0.4.00 ')).length, 5);
assert.ok(demoTitles.every(title => !title.includes('0.4.01')));
const home = fs.readFileSync(path.join(productDir, '../index.html'), 'utf8');
const homeDownloads = [...home.matchAll(/href="(https:\/\/github\.com\/dreamcall520\/emotion-ball-desktop-pet\/releases\/download\/[^\"]+)"/g)];
assert.equal(homeDownloads.length, 3);
assert.ok(homeDownloads.every(m => /\/v0\.4\.3\/Qiuqiu-0\.4\.03-macOS-arm64(?:-share\.zip|\.dmg)$/.test(m[1])));
assert.match(home, /0\.4\.03 · Apple 芯片/);
assert.match(html, /v0\.3\.13\/Qiuqiu-0\.3\.13-macOS-x64-share\.zip/);
assert.match(html, /下载并解压 ZIP/);
assert.match(html, /得到「球球桌宠\.app」/);
assert.doesNotMatch(html, /class="install-list"|codex-pet-row|可操作演示 ·/);
assert.match(html, /assets\/macos-privacy-security-open-anyway\.png/);
assert.doesNotMatch(html, /幻彩云|圆角方|尚不包含此功能/);
for (const ref of html.matchAll(/(?:src|href)="([^"#][^"]+)"/g)) {
  const file = ref[1].split('?')[0];
  if (!/^https?:/.test(file)) assert.ok(fs.existsSync(path.join(productDir, file)), `missing ${file}`);
}
console.log('Functionality page: retained demos, moved history, release downloads and local resources passed');
