/* Existing Playwright + Chrome; no extra dependencies. Run against local or published site. */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require('playwright');
const base = process.env.QIUQIU_SITE_URL || 'http://127.0.0.1:4186/';
const out = process.env.QIUQIU_QA_OUTPUT || '/tmp/qiuqiu-website-native';
fs.mkdirSync(out, { recursive: true });
(async () => {
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  const errors = [], failed = [];
  const report = { url: base, browser: 'Chrome / existing Playwright', interactions: [], layouts: [], errors, failed };
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    await page.addInitScript(() => localStorage.setItem('umami.disabled', '1'));
    page.on('pageerror', e => errors.push(e.message));
    page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
    page.on('response', r => { if (r.status() >= 400) failed.push(`${r.status()} ${r.url()}`); });
    page.on('requestfailed', r => failed.push(`${r.failure()?.errorText} ${r.url()}`));
    await page.goto(base);
    await page.evaluate(() => document.querySelectorAll('iframe[data-app-demo]').forEach(frame => frame.loading = 'eager'));
    await page.waitForFunction(() => [...document.querySelectorAll('iframe[data-app-demo]')].every(frame => frame.contentDocument?.readyState === 'complete' && frame.contentWindow.location.pathname === new URL(frame.src).pathname));
    await page.waitForTimeout(200);
    assert.equal(await page.evaluate(() => scrollY), 0, 'embedded App startup must not move the website');
    assert.match(await page.title(), /球球桌宠/);
    assert.equal(await page.locator('.milestone-update time').innerText(), '2026-10-06');
    assert.equal(await page.locator('.app-capture, .download-checks, [data-showcase-try]').count(), 0);
    assert.equal(await page.locator('.install-visual-step').count(), 3);
    assert.equal(await page.locator('[data-motion-scene] [data-ball-host] svg').count(), 3);
    assert.equal(await page.locator('.install-list, .codex-pet-row').count(), 0);
    assert.equal(await page.locator('.section-entry, .chat-download-link').count(), 0);
    assert.equal(await page.locator('.section-howto').count(), 4);
    for (const id of ['chat', 'customize', 'notes', 'appearance']) {
      const howto = page.locator(`#${id} .section-howto`);
      assert.equal(await howto.locator('p').isVisible(), false);
      await howto.locator('summary').focus(); await page.keyboard.press('Enter');
      assert.match(await howto.locator('p').innerText(), /右键球球/);
      assert.equal(await howto.locator('p').isVisible(), true);
      await page.keyboard.press('Enter');
      assert.equal(await howto.locator('p').isVisible(), false);
    }
    const typography = await page.locator('.hero-lead, .section-lead').evaluateAll(elements => elements.map(e => {
      const css=getComputedStyle(e); return {fontSize:parseFloat(css.fontSize),lineHeight:parseFloat(css.lineHeight),fontWeight:Number(css.fontWeight)};
    }));
    assert.ok(typography.every(t => t.fontSize >= 16 && t.fontSize <= 20 && t.lineHeight / t.fontSize >= 1.7 && t.fontWeight <= 450));
    report.interactions.push('consistent introduction typography; four keyboard-operable opening instructions; no standalone entry footnotes or extra chat download CTA');
    const pause = page.locator('.hero-motion-toggle');
    assert.equal(await pause.evaluate(e => getComputedStyle(e).borderWidth), '0px');
    assert.equal(await pause.locator('svg').evaluate(e => getComputedStyle(e).width), '18px');
    await pause.click();
    assert.equal(await pause.getAttribute('aria-label'), '继续动效');
    assert.equal(await page.evaluate(() => window.QiuqiuWebsiteMotion.getState().find(s => s.name === 'hero').paused), true);
    await pause.click();
    assert.equal(await pause.getAttribute('aria-label'), '暂停动效');
    await page.locator('.hero-stage [data-pet-touch]').focus(); await page.keyboard.press('Tab');
    assert.equal(await pause.evaluate(e => e === document.activeElement && getComputedStyle(e).outlineWidth === '2px'), true);
    const feature = page.locator('.feature-playground');
    const edge = feature.locator('[data-desktop-edge]');
    const edgeNotice = feature.locator('[data-feature-edge-notice]');
    await feature.scrollIntoViewIfNeeded(); await edge.check();
    assert.equal(await edgeNotice.isVisible(), true);
    assert.match(await edgeNotice.innerText(), /5 小时 · 剩余 82%/);
    assert.equal(await edgeNotice.evaluate(e => getComputedStyle(e).pointerEvents), 'none');
    await feature.locator('[data-pet-touch]').focus();
    assert.equal(await edgeNotice.isVisible(), false, 'peek withdraws the quota capsule');
    await edge.focus(); await edge.uncheck(); await edge.check();
    assert.match(await edgeNotice.innerText(), /周额度 · 剩余 68%/);
    await page.waitForFunction(() => document.querySelector('[data-feature-edge-notice]').hidden, null, { timeout: 8000 });
    await edge.uncheck();
    report.interactions.push('public edge quota capsule; pointer-transparent; focus peek withdraws; two period examples and 6-second dismissal');
    await page.locator('#install').scrollIntoViewIfNeeded();
    await page.waitForFunction(() => { const img = document.querySelector('.install-settings img'); return img.complete && img.naturalWidth === 1430; });
    assert.equal(await page.locator('.install-settings-guide').isVisible(), true);
    assert.equal(await page.locator('.install-settings-label').innerText(), '③ 仍要打开');
    const imageLink = page.locator('[data-image-preview]');
    assert.equal(await imageLink.getAttribute('target'), null);
    const tabsBefore = page.context().pages().length;
    await imageLink.click();
    const imageDialog = page.locator('[data-image-preview-dialog]');
    await imageDialog.waitFor({ state: 'visible' });
    assert.equal(page.context().pages().length, tabsBefore, 'image stays in the current page');
    assert.equal(await imageDialog.locator('.install-settings-guide').isVisible(), true);
    assert.equal(await page.locator('html').evaluate(e => getComputedStyle(e).overflow), 'hidden');
    await imageDialog.screenshot({ path: path.join(out, 'installation-preview-1440-light.png') });
    await page.keyboard.press('Escape');
    assert.equal(await imageDialog.isVisible(), false);
    assert.equal(await imageLink.evaluate(e => e === document.activeElement), true);
    await imageLink.click(); await page.getByRole('button', { name: '关闭图片预览' }).click();
    await imageLink.click(); await page.mouse.click(2, 2);
    assert.equal(await imageDialog.isVisible(), false, 'backdrop click closes the preview');
    await page.waitForFunction(() => !document.documentElement.classList.contains('image-preview-open'));
    assert.notEqual(await page.locator('html').evaluate(e => getComputedStyle(e).overflow), 'hidden');
    report.interactions.push('native image dialog; no new tab; original image and guide retained; Esc/close/backdrop/focus/scroll lock');
    assert.equal(await page.locator('body').innerText().then(text => /可操作演示 ·|网页演示不连接账户|不保存输入/.test(text)), false);
    assert.match(await page.locator('.button-primary').first().evaluate(e => getComputedStyle(e).backgroundImage), /52, 61, 72/);
    await page.locator('#chat').scrollIntoViewIfNeeded();
    const chat = page.frameLocator('#chat iframe');
    await chat.locator('#chat-avatar[data-avatar-ready="true"]').waitFor();
    await page.locator('#customize').scrollIntoViewIfNeeded();
    const custom = page.frameLocator('#customize iframe');
    await custom.locator('#save').waitFor();
    const before = await chat.locator('#chat-avatar').getAttribute('data-shape');
    await custom.locator('button[data-shape="cloud"]').click();
    assert.equal(await chat.locator('#chat-avatar').getAttribute('data-shape'), before, 'draft must not change saved avatar');
    await custom.locator('#body-hex').fill('#5874AB'); await custom.locator('#body-hex').press('Tab');
    await custom.locator('#preset-add').click(); await custom.locator('#preset-name').fill('蓝色云朵'); await custom.locator('#preset-submit').click();
    await custom.locator('#preset-list').getByText('蓝色云朵', { exact: true }).waitFor();
    await custom.locator('#save').click();
    await page.waitForFunction(() => document.querySelector('#chat iframe').contentDocument.querySelector('#chat-avatar').dataset.shape === 'cloud');
    await page.locator('#chat').scrollIntoViewIfNeeded();
    await chat.locator('#new-chat').click(); await chat.locator('#cancel-new-chat').click();
    await chat.locator('#new-chat').click(); await chat.locator('#confirm-new-chat').click();
    await chat.locator('#message-input').fill('想慢慢完成今天的事。'); await chat.locator('#send-message').click();
    await chat.getByText('先慢一点，挑一件想说的事，我们接着聊。', { exact: true }).waitFor();
    await chat.locator('#chat-history').click(); await chat.locator('.history-item').filter({ hasText: '给今天留一点空隙' }).click();
    assert.equal(await chat.locator('.message').count(), 2);
    await chat.locator('#close-chat').click(); await chat.locator('#demo-reopen').click();
    report.interactions.push('real customizer collection and save-only avatar sync; real chat new/cancel/send/history/close/reopen');
    await page.locator('#notes').scrollIntoViewIfNeeded();
    const panel = page.frameLocator('[data-notes-frame="panel"]');
    const desktop = () => page.frameLocator('[data-notes-frame="desktop"]');
    await desktop().locator('#desktop-body').fill('去公园走走；记得带水和相机。');
    await panel.locator('.note-preview').filter({ hasText: '去公园走走；记得带水和相机。' }).waitFor();
    await desktop().locator('#desktop-more').click(); await desktop().locator('#actions-list').getByRole('button', { name: '智能整理', exact: true }).click();
    await desktop().locator('#organize-generate').click();
    assert.equal(await desktop().locator('#desktop-body').inputValue(), '去公园走走；记得带水和相机。');
    await desktop().locator('#organize-apply').click();
    await desktop().locator('#toast').getByRole('button', { name: '撤销', exact: true }).click();
    await desktop().locator('#hide-note').click(); await page.locator('[data-notes-reopen-note]').click();
    assert.equal(await desktop().locator('#desktop-body').inputValue(), '去公园走走；记得带水和相机。');
    await page.locator('[data-notes-demo-reminder]').click();
    await desktop().getByRole('button', { name: '稍后10分钟', exact: true }).click();
    await page.locator('[data-notes-demo-reset]').click();
    await page.waitForFunction(() => { const frame = document.querySelector('[data-notes-frame="panel"]'); return frame.contentWindow.location.href === frame.src && frame.contentDocument.readyState === 'complete' && frame.contentDocument.querySelectorAll('#records .record').length === 3; });
    await panel.locator('#hide-panel').click(); await page.locator('[data-notes-reopen-panel]').click();
    report.interactions.push('native notes cross-frame save, organize preview/apply/undo, close/reopen, reminder snooze, reset');
    await page.locator('#codex').scrollIntoViewIfNeeded();
    const codexEdges = await page.locator('#codex').evaluate(e => [e.querySelector('h2'), e.querySelector('.codex-live-showcase'), e.querySelector('.fact-list')].map(n => n.getBoundingClientRect().left));
    assert.ok(Math.max(...codexEdges) - Math.min(...codexEdges) < 1, 'Codex title, demo and benefits share the same left edge');
    const quota = page.frameLocator('#codex iframe').frameLocator('#quota-frame');
    const detail = page.frameLocator('#codex iframe').frameLocator('#detail-frame');
    await detail.locator('.trend-chart').waitFor();
    const cardWidth = await page.frameLocator('#codex iframe').locator('#quota-frame').evaluate(e => e.getBoundingClientRect().width);
    assert.ok(Math.abs(cardWidth - 280) < 1, `quota card enlarged to 280px: ${cardWidth}`);
    assert.equal(await page.frameLocator('#codex iframe').locator('#demo-feedback').isVisible(), false);
    const quotaDemo = page.frameLocator('#codex iframe');
    const task = page.locator('.codex-task-demo');
    const taskCenters = await task.locator('.motion-stage, .codex-task-status, h3, [data-task-next]').evaluateAll(elements => elements.map(e => { const r=e.getBoundingClientRect(); return r.left+r.width/2; }));
    assert.ok(Math.max(...taskCenters)-Math.min(...taskCenters)<1, 'pet, task status, title and button share the center');
    assert.equal(await task.evaluate(e => getComputedStyle(e).borderBottomWidth), '0px');
    const quotaGap = await task.evaluate(e => e.nextElementSibling.getBoundingClientRect().top-e.getBoundingClientRect().bottom);
    assert.ok(quotaGap >= 0 && quotaGap <= 16, `task-to-quota gap: ${quotaGap}`);
    assert.equal(await quotaDemo.locator('.demo-toolbar').evaluate(e => getComputedStyle(e).borderBottomWidth), '0px');
    await task.scrollIntoViewIfNeeded();
    const taskState = () => page.evaluate(() => QiuqiuWebsiteMotion.getState().find(s => s.name === 'codex'));
    await page.waitForFunction(() => QiuqiuWebsiteMotion.getState().find(s => s.name === 'codex').thought.running);
    assert.equal(await task.getAttribute('data-task-state'), 'processing');
    assert.match(await quota.locator('[data-action="tasks"]').innerText(), /1/);
    assert.doesNotMatch(await quota.locator('[data-action="results"]').innerText(), /1/);
    await task.locator('[data-motion-toggle]').click();
    assert.equal((await taskState()).thought.running, false);
    assert.equal((await taskState()).timers, 0);
    await task.locator('[data-motion-toggle]').click();
    await page.evaluate(() => window.postMessage({ type: 'qiuqiu-demo-task-state', state: 'completed' }, location.origin));
    await page.waitForTimeout(50);
    assert.equal(await task.getAttribute('data-task-state'), 'processing', 'only the known quota frame can change task state');
    await task.locator('[data-task-next]').click();
    await page.waitForFunction(() => document.querySelector('#codex iframe').contentWindow.QiuqiuQuotaDemo.getState().taskState === 'completed');
    assert.equal((await taskState()).action, 'complete');
    assert.equal((await taskState()).thought.running, false);
    assert.match(await quota.locator('[data-action="results"]').innerText(), /1/);
    await task.screenshot({ path: path.join(out, 'task-completed-1440-light.png') });
    const taskFrame = page.frames().find(frame => /\/demos\/quota\/index\.html/.test(frame.url()) && !frame.url().includes('appearanceDemo'));
    await taskFrame.goto(taskFrame.url());
    await page.waitForFunction(() => document.querySelector('#codex iframe').contentWindow.QiuqiuQuotaDemo?.getState().taskState === 'completed');
    assert.equal(await task.getAttribute('data-task-state'), 'completed', 'iframe startup preserves the latest task command');
    await task.locator('[data-task-next]').click();
    await quotaDemo.locator('#demo-thread').waitFor({ state: 'visible' });
    assert.equal(await task.getAttribute('data-task-state'), 'viewed');
    assert.doesNotMatch(await quota.locator('[data-action="results"]').innerText(), /1/);
    await quotaDemo.locator('#thread-close').click();
    await task.locator('[data-task-next]').click();
    await task.locator('[data-task-next]').click();
    await quota.locator('[data-action="results"]').click();
    await detail.locator('[data-thread-id="demo-notes"]').click();
    await page.waitForFunction(() => document.querySelector('.codex-task-demo').dataset.taskState === 'viewed');
    await quotaDemo.locator('#thread-close').click(); await task.locator('[data-task-next]').click();
    report.interactions.push('task-linked thought trails, completion celebration and unread count; result view and native result click sync; pause and trusted frame source');
    const align = await quotaDemo.locator('.demo-layout').evaluate(e => Math.abs(e.querySelector('.demo-cards').getBoundingClientRect().top - e.querySelector('.demo-detail').getBoundingClientRect().top));
    assert.ok(align < 1, `cards and trend top aligned: ${align}`);
    const scenario = quotaDemo.locator('#demo-scenario');
    await scenario.click(); await scenario.selectOption('fast');
    assert.equal(await scenario.evaluate(e => getComputedStyle(e).outlineStyle), 'none', 'mouse selection leaves no focus ring');
    await scenario.press('Tab'); await page.keyboard.press('Shift+Tab');
    assert.equal(await scenario.evaluate(e => e === document.activeElement && getComputedStyle(e).outlineWidth === '1px'), true, 'keyboard focus remains visible');
    await scenario.selectOption('balanced');
    for (const [cardPeriod, count, title] of [['5h',1,/5 小时趋势/],['week',1,/周额度趋势/],['dual',2,/额度趋势/]]) {
      await quotaDemo.locator(`[data-card-period="${cardPeriod}"]`).click();
      await page.waitForFunction(value => document.querySelector('#codex iframe').contentWindow.QiuqiuQuotaDemo.getState().cardPeriod === value, cardPeriod);
      await page.waitForFunction(({count,cardPeriod}) => {
        const demo=document.querySelector('#codex iframe').contentDocument;
        const title=demo.querySelector('#detail-frame').contentDocument.querySelector('#details-title').textContent.trim();
        return demo.querySelector('#quota-frame').contentDocument.querySelectorAll('.v20-period').length===count && title.startsWith(cardPeriod==='5h'?'5 小时趋势':cardPeriod==='week'?'周额度趋势':'额度趋势');
      }, {count,cardPeriod});
      assert.equal(await quota.locator('.v20-period').count(), count);
      assert.match(await detail.locator('#details-title').innerText(), title);
      assert.equal(await page.locator('[data-demo-appearance][data-demo="quota"]').evaluate(e => e.contentWindow.QiuqiuQuotaDemo.getState().cardPeriod), 'dual');
      await quotaDemo.locator('.demo-layout').screenshot({ path: path.join(out, `quota-${cardPeriod}-1440-light.png`) });
    }
    await quota.locator('[data-action="opportunities"]').click(); await detail.locator('.opportunity-history > summary').click();
    assert.match(await detail.locator('.opportunity-history').innerText(), /已获得/);
    await quota.locator('[data-action="trend"]').click(); await detail.locator('[data-period="300"]').click();
    assert.match(await detail.locator('#details-content').innerText(), /82%/);
    report.interactions.push('native quota default trend, aligned columns, mouse/keyboard scenario focus, history and period switching');
    await page.locator('#appearance').scrollIntoViewIfNeeded();
    const appearanceAligned = async () => {
      await page.waitForFunction(() => {
        const preview=document.querySelector('.native-appearance-preview'), frames=[...preview.querySelectorAll(':scope > iframe')], rects=frames.map(f=>f.getBoundingClientRect());
        const singleColumn=getComputedStyle(preview).gridTemplateColumns.trim().split(/\s+/).length===1;
        return rects.every(r=>r.height>100) && (singleColumn || (Math.abs(rects[0].top-rects[1].top)<1 && Math.abs(rects[0].bottom-rects[1].bottom)<1));
      });
    };
    await page.locator('[data-ap-mode="accessible"]').click(); await page.locator('[data-ap-look="dark"]').click();
    const appearanceChat = page.frameLocator('[data-demo-appearance][data-demo="chat"]');
    await appearanceChat.locator('html[data-color-mode="accessible"]').waitFor();
    assert.equal(await appearanceChat.locator('html').getAttribute('data-accessible-appearance'), 'dark');
    assert.equal(await chat.locator('html').getAttribute('data-color-mode'), 'standard');
    assert.equal(await page.locator('[data-demo-appearance][data-demo="quota"]').evaluate(e => getComputedStyle(e).backgroundColor), 'rgb(24, 33, 37)');
    await page.locator('[data-ap-look="light"]').click();
    assert.equal(await page.locator('[data-demo-appearance][data-demo="quota"]').evaluate(e => getComputedStyle(e).backgroundColor), 'rgb(246, 248, 251)');
    assert.equal(await page.locator('[data-demo-appearance][data-demo="quota"]').evaluate(e => getComputedStyle(e).colorScheme), 'light');
    for (const look of ['light', 'dark']) {
      await page.locator(`[data-ap-look="${look}"]`).click();
      await appearanceChat.locator(`html[data-accessible-appearance="${look}"]`).waitFor();
      assert.equal(await page.locator('[data-demo-appearance][data-demo="quota"]').evaluate(e => getComputedStyle(e).colorScheme), look);
      const corners = await appearanceChat.locator('.chat-panel').evaluate(e => {
        const r = e.getBoundingClientRect(), css = getComputedStyle(e);
        return { inset: r.left >= 1 && r.top >= 1 && r.right <= innerWidth - 1 && r.bottom <= innerHeight - 1, radius: css.borderTopLeftRadius, border: css.borderTopWidth };
      });
      assert.deepEqual(corners, { inset: true, radius: '15px', border: '1px' });
      assert.equal(await appearanceChat.locator('#privacy-note').isVisible(), false);
      for (const cardPeriod of ['5h','week','dual']) {
        await page.frameLocator('[data-demo-appearance][data-demo="quota"]').locator(`[data-card-period="${cardPeriod}"]`).click();
        await appearanceAligned();
        assert.equal(await quotaDemo.locator('body').evaluate(() => QiuqiuQuotaDemo.getState().cardPeriod), 'dual');
      }
      await page.locator('#appearance').screenshot({ path: path.join(out, `appearance-1440-accessible-${look}.png`) });
    }
    await page.locator('[data-ap-look="system"]').click();
    await page.emulateMedia({ colorScheme: 'dark' });
    assert.equal(await page.locator('[data-demo-appearance][data-demo="quota"]').evaluate(e => getComputedStyle(e).backgroundColor), 'rgb(24, 33, 37)');
    await page.emulateMedia({ colorScheme: 'light' });
    const appearanceDemo = page.frameLocator('[data-demo-appearance][data-demo="quota"]');
    const appearanceQuota = appearanceDemo.frameLocator('#quota-frame');
    const appearanceApi = appearanceDemo.frameLocator('#api-label-frame');
    await appearanceQuota.locator('[data-action="tasks"]').click();
    await appearanceQuota.locator('.v20-collapse').click();
    await appearanceApi.locator('#quota-label').press('Enter');
    await page.waitForFunction(() => {
      const state=document.querySelector('[data-demo-appearance][data-demo="quota"]').contentWindow.QiuqiuQuotaDemo.getState();
      return state.action==='tasks' && !state.expanded && !state.apiExpanded;
    });
    const draft='这一段用于检查长输入时聊天底部按钮是否完整。\n'.repeat(28);
    await appearanceChat.locator('#message-input').fill(draft);
    await appearanceAligned();
    const composerFits = () => appearanceChat.locator('.composer').evaluate(e => e.getBoundingClientRect().bottom <= innerHeight);
    assert.equal(await composerFits(), true, 'long draft remains inside the shortest shared preview');
    assert.ok(await appearanceChat.locator('body').evaluate(() => innerHeight >= 480));
    await appearanceChat.locator('#chat-history').click();
    await appearanceChat.locator('.history-item').filter({hasText:'给今天留一点空隙'}).click();
    assert.equal(await composerFits(), true);
    await appearanceChat.locator('#message-input').fill('');
    await appearanceQuota.locator('#quota-label').press('Enter');
    await appearanceApi.locator('#quota-label').press('Enter');
    await appearanceQuota.locator('[data-action="trend"]').click();
    report.interactions.push('native dual/5-hour/weekly cards and matching trend; independent instances; appearance top and bottom alignment across card and theme changes; centered task reminder; complete chat corners');
    await page.reload();
    for (const [width, theme] of [[1440,'light'],[1440,'dark'],[1080,'light'],[1080,'dark'],[390,'light'],[390,'dark'],[320,'light'],[320,'dark']]) {
      await page.setViewportSize({ width, height: width > 600 ? 1000 : 844 });
      await page.evaluate(theme => document.documentElement.dataset.theme = theme, theme);
      for (const id of ['top','features','codex','chat','customize','notes','appearance','download','install','updates']) {
        const section = page.locator(`#${id}`); await section.scrollIntoViewIfNeeded();
        await page.waitForTimeout(100);
        assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), `outer overflow ${width}/${theme}/${id}`);
        const overflow = await page.evaluate(() => [...document.querySelectorAll('iframe[data-app-demo]')].filter(f => f.contentDocument?.readyState === 'complete').flatMap(f => [f, ...f.contentDocument.querySelectorAll('iframe')]).filter(f => !f.hidden && f.contentWindow?.innerWidth > 0 && f.contentDocument?.documentElement.scrollWidth > f.contentWindow.innerWidth + 1).map(f => f.src));
        assert.deepEqual(overflow, [], `embedded overflow ${width}/${theme}/${id}`);
        if (id === 'codex') assert.equal(await page.locator('#codex iframe').evaluate(e => getComputedStyle(e).colorScheme), theme, 'quota host scheme matches its transparent embedded page');
        if (id === 'appearance') await appearanceAligned();
        if (id === 'features') {
          await edge.uncheck(); await edge.check();
          await page.waitForTimeout(450);
          const fits = await edgeNotice.evaluate(e => { const r=e.getBoundingClientRect(), parent=e.parentElement.getBoundingClientRect(); return r.left >= parent.left && r.right <= parent.right && e.scrollWidth <= e.clientWidth + 1; });
          assert.equal(fits, true, `edge capsule fits ${width}/${theme}`);
          await feature.screenshot({ path: path.join(out, `edge-quota-${width}-${theme}.png`) });
          await edge.uncheck();
        }
        if (id === 'install') {
          await page.locator('[data-image-preview]').click();
          const dialog = page.locator('[data-image-preview-dialog]');
          assert.equal(await dialog.evaluate(e => { const r=e.getBoundingClientRect(); return r.left >= 0 && r.right <= innerWidth && r.top >= 0 && r.bottom <= innerHeight; }), true);
          await dialog.screenshot({ path: path.join(out, `installation-preview-${width}-${theme}.png`) });
          await page.keyboard.press('Escape');
        }
      }
      await page.evaluate(() => document.querySelectorAll('.site-header,.skip-link,[data-back-to-top]').forEach(e => e.style.setProperty('opacity', '0', 'important')));
      const ids = width >= 1080 || (width === 390 && theme === 'light') ? ['top','codex','customize','notes','appearance','download','install'] : ['customize','notes'];
      for (const id of ids) await page.locator(`#${id}`).screenshot({ path: path.join(out, `${id}-${width}-${theme}.png`) });
      report.layouts.push({ width, theme, horizontalOverflow: false });
    }
    await page.emulateMedia({ reducedMotion: 'reduce', colorScheme: 'dark' });
    await page.evaluate(() => document.documentElement.removeAttribute('data-theme'));
    await page.locator('.codex-task-demo').scrollIntoViewIfNeeded();
    await page.locator('.codex-task-demo [data-task-next]').click();
    const reducedTask = await taskState();
    assert.equal(reducedTask.playing, false); assert.equal(reducedTask.thought.running, false);
    assert.equal(await page.locator('.codex-task-demo [data-motion-toggle]').isDisabled(), true);
    await page.locator('#chat').scrollIntoViewIfNeeded();
    await chat.locator('html[data-accessible-appearance="dark"]').waitFor();
    assert.equal(await chat.locator('#chat-avatar').getAttribute('data-avatar-active'), 'false');
    assert.equal(await page.locator('html').evaluate(e => getComputedStyle(e).getPropertyValue('--page').trim()), '#11151b');
    assert.deepEqual(errors, []); assert.deepEqual(failed, []);
    report.reducedMotion = 'passed'; report.systemDark = 'passed';
    fs.writeFileSync(path.join(out, 'browser-verification.json'), JSON.stringify(report, null, 2));
    console.log(JSON.stringify(report, null, 2));
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
