/* Run with NODE_PATH pointing to an existing Playwright installation and a local server. */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require('playwright');
const base = process.env.QIUQIU_SITE_URL || 'http://127.0.0.1:4184/';
const out = process.env.QIUQIU_QA_OUTPUT || '/tmp/qiuqiu-website-0400';
fs.mkdirSync(out, { recursive: true });
(async () => {
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  const report = { url: base, browser: 'Chrome via bundled Playwright; Browser plugin not available', layouts: [], interactions: [] };
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    await page.addInitScript(() => localStorage.setItem('umami.disabled', '1'));
    const errors = [], failed = [];
    page.on('pageerror', e => errors.push(e.message));
    page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
    page.on('response', r => { if (r.status() >= 400) failed.push(`${r.status()} ${r.url()}`); });
    await page.goto(base);
    for (const demo of await page.locator('[data-showcase-try] > summary').all()) await demo.click();
    await page.waitForFunction(() => getComputedStyle(document.querySelector('.customize-layout')).display === 'grid');
    assert.match(await page.title(), /球球桌宠/);
    assert.equal(await page.locator('[data-motion-error]').count(), 0);
    assert.equal(await page.locator('[data-motion-scene] [data-ball-host] svg').count(), 3);
    assert.ok((await page.locator('main').innerText()).includes('0.4.00'));
    const custom = page.locator('[data-customize-demo]');
    const avatar = page.locator('[data-custom-chat-avatar]');
    await custom.locator('[data-custom-body]').fill('#ddeadf');
    await custom.locator('[data-custom-save]').click();
    assert.equal(await avatar.getAttribute('data-shape'), 'blob');
    await custom.locator('[data-custom-shape="cloud"]').click();
    assert.equal(await avatar.getAttribute('data-shape'), 'blob', 'preview must not change saved avatar');
    await custom.locator('[data-custom-name]').fill('暮色云朵');
    await custom.locator('[data-custom-collect]').click();
    await custom.locator('[data-custom-save]').click();
    assert.equal(await avatar.getAttribute('data-shape'), 'cloud');
    await custom.locator('[data-custom-shape="square"]').click();
    await custom.locator('[data-custom-presets] button').click();
    assert.equal(await custom.locator('[data-custom-shape="cloud"]').getAttribute('aria-pressed'), 'true');
    assert.match(await custom.locator('[data-custom-startup-note]').innerText(), /保存后才应用/);
    await custom.locator('[data-custom-shape="aurora"]').click();
    await custom.locator('[data-custom-style="simple"]').click();
    await custom.locator('[data-custom-opacity]').fill('60');
    assert.equal(await custom.locator('[data-custom-opacity-label]').innerText(), '60%');
    assert.equal(await custom.locator('[data-custom-artwork]').evaluate(e => e.style.opacity), '0.4');
    await custom.locator('[data-custom-save]').click();
    assert.match(await avatar.locator('img').getAttribute('src'), /custom-aurora-simple/);
    await custom.locator('[data-custom-reset]').click();
    assert.equal(await custom.locator('[data-custom-shape="aurora"]').getAttribute('aria-pressed'), 'true');
    await custom.locator('[data-custom-shape="blob"]').click();
    await custom.locator('[data-custom-save]').click();
    report.interactions.push('four shapes, palette, opacity, named collection load, save-only avatar sync');
    const chat = page.locator('[data-chat-demo]');
    const firstChat = await chat.locator('[data-chat-messages]').innerText();
    await chat.locator('[data-chat-new]').click(); await chat.locator('[data-chat-cancel]').click();
    assert.equal(await chat.locator('[data-chat-messages]').innerText(), firstChat);
    await chat.locator('[data-chat-new]').click(); await chat.locator('[data-chat-create]').click();
    await chat.locator('[data-chat-send]').click();
    await page.waitForFunction(() => document.querySelector('[data-chat-messages]').textContent.includes('想从什么聊起'));
    await chat.locator('[data-chat-history]').click(); await chat.locator('[data-chat-select="today"]').click();
    assert.equal(await chat.locator('[data-chat-messages]').innerText(), firstChat);
    await chat.locator('[data-chat-close]').click(); await page.locator('[data-chat-reopen]').click();
    assert.equal(await chat.isVisible(), true);
    report.interactions.push('new chat cancellation, send example, return to preserved history, close/reopen');
    const notes = page.locator('[data-notes-demo]');
    const original = await notes.locator('[data-notes-body]').inputValue();
    await notes.locator('[data-notes-organize]').click(); await notes.locator('[data-notes-generate]').click();
    assert.equal(await notes.locator('[data-notes-body]').inputValue(), original, 'preview keeps original');
    await notes.locator('[data-notes-apply]').click();
    assert.notEqual(await notes.locator('[data-notes-body]').inputValue(), original);
    await notes.locator('[data-notes-undo]').click(); assert.equal(await notes.locator('[data-notes-body]').inputValue(), original);
    await notes.locator('[data-notes-filter]').selectOption('favorites'); assert.equal(await notes.locator('.notes-record').count(), 1);
    await notes.locator('[data-notes-search]').fill('no-such-note'); assert.match(await notes.locator('[data-notes-records]').innerText(), /没有匹配/);
    await notes.locator('[data-notes-reset]').click(); await notes.locator('[data-notes-close-note]').click();
    assert.match(await notes.locator('[data-notes-closed]').innerText(), /内容保留/);
    await notes.locator('[data-notes-open-note]').click();
    await notes.locator('[data-notes-tab="todo"]').click();
    const reminder = await notes.locator('[data-notes-reminder-time]').inputValue();
    await notes.locator('[data-notes-due]').fill('2026-10-20');
    assert.equal(await notes.locator('[data-notes-reminder-time]').inputValue(), reminder);
    await notes.locator('[data-notes-show-reminder]').click(); await notes.locator('[data-notes-snooze]').click();
    assert.match(await notes.locator('[data-notes-status]').innerText(), /10 分钟后/);
    await notes.locator('[data-notes-show-reminder]').click(); await notes.locator('[data-notes-reminder-complete]').click();
    const completed = notes.locator('.notes-record').filter({ hasText: '给自己留一点休息时间' });
    assert.equal(await completed.locator('.notes-check').getAttribute('aria-pressed'), 'true');
    await completed.locator('summary').click(); await completed.getByRole('button', { name: '归档已完成' }).click();
    await notes.locator('[data-notes-filter]').selectOption('archived');
    const archived = notes.locator('.notes-record').filter({ hasText: '给自己留一点休息时间' });
    await archived.getByRole('button', { name: '恢复', exact: true }).click();
    await notes.locator('[data-notes-tab="note"]').click(); await notes.locator('[data-notes-filter]').selectOption('trash');
    await notes.getByRole('button', { name: '恢复', exact: true }).click();
    await notes.locator('[data-notes-filter]').selectOption('all');
    assert.equal(await notes.locator('.notes-record').count(), 4);
    await notes.locator('[data-notes-reset]').click();
    report.interactions.push('notes filters/search, desktop close/reopen, organize preview/replace/undo, independent due/reminder, snooze/complete/archive/restore/trash');
    const quota = page.locator('[data-quota-demo]');
    await quota.locator('[data-qd-detail="trend"]').click();
    assert.match(await quota.locator('.qd-detail').innerText(), /趋势/);
    await quota.locator('[data-qd-forecast]').click();
    assert.match(await quota.locator('.qd-detail').innerText(), /暂无法预估额度用完时间/);
    await quota.locator('[data-qd-forecast]').click();
    await quota.locator('.qd-shared [data-qd-detail="opportunities"]').click();
    await quota.locator('.qd-history > summary').click();
    assert.match(await quota.locator('.qd-history').innerText(), /记录|历史/);
    await quota.locator('.qd-links [data-qd-detail="tasks"]').click();
    await quota.locator('[data-qd-task]').first().click();
    assert.match(await quota.innerText(), /示例/);
    await quota.locator('.qd-api-card [data-qd-detail="api"]').click(); assert.match(await quota.innerText(), /USD|tokens/);
    await quota.locator('.qd-links [data-qd-detail="results"]').click();
    await quota.locator('[data-qd-task="result"]').click();
    assert.equal(await quota.locator('[data-qd-unread]').innerText(), '0');
    await quota.locator('[data-qd-close]').click();
    await quota.locator('.qd-chevron').click();
    assert.equal(await quota.locator('.qd-compact').isVisible(), true);
    await quota.locator('.qd-compact').click();
    await quota.locator('.qd-links [data-qd-detail="trend"]').click();
    report.interactions.push('quota compact/expanded, trend/insufficient-history forecast, reset history, task/viewed-result and separate API report');
    await page.locator('[data-desktop-edge]').check();
    const touch = page.locator('#features [data-pet-touch]'); await touch.hover();
    assert.equal(await page.locator('#features [data-motion-scene]').getAttribute('data-edge-tucked'), 'false');
    await page.locator('[data-desktop-edge]').uncheck();
    report.interactions.push('existing pet interactions and edge expansion retained with public renderer');
    await quota.locator('[data-qd-close]').click();
    for (const demo of await page.locator('[data-showcase-try] > summary').all()) await demo.click();
    for (const [width, theme] of [[1440,'light'],[1440,'dark'],[390,'light'],[390,'dark'],[320,'light'],[320,'dark']]) {
      await page.setViewportSize({ width, height: width > 600 ? 1000 : 844 });
      await page.evaluate(theme => document.documentElement.dataset.theme = theme, theme);
      for (const id of ['top','chat','customize','notes','codex','updates']) {
        const section = page.locator(`#${id}`); await section.scrollIntoViewIfNeeded();
        assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), `horizontal overflow ${width}/${theme}/${id}`);
      }
      for (const id of ['chat','customize','notes','codex']) await page.locator(`#${id}`).screenshot({ path: path.join(out, `${id}-${width}-${theme}.png`), style: '.site-header, .skip-link, [data-back-to-top] { visibility: hidden !important; opacity: 0 !important; }' });
      report.layouts.push({ width, theme, horizontalOverflow: false });
    }
    await page.emulateMedia({ reducedMotion: 'reduce', colorScheme: 'dark' });
    await page.evaluate(() => document.documentElement.removeAttribute('data-theme'));
    await page.locator('#codex').scrollIntoViewIfNeeded();
    assert.equal(await page.evaluate(() => window.QiuqiuQuotaDemo.getState().autoPlaying), false);
    await page.locator('#customize').scrollIntoViewIfNeeded();
    assert.equal(await page.locator('.customize-layout').evaluate(e => getComputedStyle(e).getPropertyValue('--accent').trim()), '#72dfc2');
    assert.deepEqual(errors, []); assert.deepEqual(failed, []);
    report.consoleErrors = errors; report.failedResources = failed; report.reducedMotion = 'passed'; report.systemDark = 'passed';
    fs.writeFileSync(path.join(out, 'browser-verification.json'), JSON.stringify(report, null, 2));
    console.log(JSON.stringify(report, null, 2));
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
