/* Existing Playwright + Chrome; no extra dependencies. Run against local or published site. */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require('playwright');
const base = process.env.QIUQIU_SITE_URL || 'http://127.0.0.1:4186/';
const out = process.env.QIUQIU_QA_OUTPUT || '/tmp/qiuqiu-website-native';
fs.mkdirSync(out, { recursive: true });
(async () => {
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  const errors = [], failed = [];
  const report = { url: base, browser: 'Chrome / existing Playwright', interactions: [], layouts: [], errors, failed };
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    await page.addInitScript(() => localStorage.setItem('umami.disabled', '1'));
    page.on('pageerror', e => errors.push(e.message));
    page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
    page.on('response', r => { if (r.status() >= 400) failed.push(`${r.status()} ${r.url()}`); });
    page.on('requestfailed', r => failed.push(`${r.failure()?.errorText} ${r.url()}`));
    await page.goto(base);
    assert.match(await page.title(), /球球桌宠/);
    assert.equal(await page.locator('.milestone-update time').innerText(), '2026-10-06');
    assert.equal(await page.locator('.app-capture, .download-checks, [data-showcase-try]').count(), 0);
    assert.equal(await page.locator('.install-visual-step').count(), 3);
    assert.equal(await page.locator('[data-motion-scene] [data-ball-host] svg').count(), 3);
    assert.match(await page.locator('.button-primary').first().evaluate(e => getComputedStyle(e).backgroundImage), /52, 61, 72/);
    await page.locator('#chat').scrollIntoViewIfNeeded();
    const chat = page.frameLocator('#chat iframe');
    await chat.locator('#chat-avatar[data-avatar-ready="true"]').waitFor();
    await page.locator('#customize').scrollIntoViewIfNeeded();
    const custom = page.frameLocator('#customize iframe');
    await custom.locator('#save').waitFor();
    const before = await chat.locator('#chat-avatar').getAttribute('data-shape');
    await custom.locator('button[data-shape="cloud"]').click();
    assert.equal(await chat.locator('#chat-avatar').getAttribute('data-shape'), before, 'draft must not change saved avatar');
    await custom.locator('#body-hex').fill('#5874AB'); await custom.locator('#body-hex').press('Tab');
    await custom.locator('#preset-add').click(); await custom.locator('#preset-name').fill('蓝色云朵'); await custom.locator('#preset-submit').click();
    await custom.locator('#preset-list').getByText('蓝色云朵', { exact: true }).waitFor();
    await custom.locator('#save').click();
    await page.waitForFunction(() => document.querySelector('#chat iframe').contentDocument.querySelector('#chat-avatar').dataset.shape === 'cloud');
    await page.locator('#chat').scrollIntoViewIfNeeded();
    await chat.locator('#new-chat').click(); await chat.locator('#cancel-new-chat').click();
    await chat.locator('#new-chat').click(); await chat.locator('#confirm-new-chat').click();
    await chat.locator('#message-input').fill('想慢慢完成今天的事。'); await chat.locator('#send-message').click();
    await chat.getByText(/网页示例回复/).waitFor();
    await chat.locator('#chat-history').click(); await chat.locator('.history-item').filter({ hasText: '给今天留一点空隙' }).click();
    assert.equal(await chat.locator('.message').count(), 2);
    await chat.locator('#close-chat').click(); await chat.locator('#demo-reopen').click();
    report.interactions.push('real customizer collection and save-only avatar sync; real chat new/cancel/send/history/close/reopen');
    await page.locator('#notes').scrollIntoViewIfNeeded();
    const panel = page.frameLocator('[data-notes-frame="panel"]');
    const desktop = () => page.frameLocator('[data-notes-frame="desktop"]');
    await desktop().locator('#desktop-body').fill('去公园走走；记得带水和相机。');
    await panel.locator('.note-preview').filter({ hasText: '去公园走走；记得带水和相机。' }).waitFor();
    await desktop().locator('#desktop-more').click(); await desktop().locator('#actions-list').getByRole('button', { name: '智能整理', exact: true }).click();
    await desktop().locator('#organize-generate').click();
    assert.equal(await desktop().locator('#desktop-body').inputValue(), '去公园走走；记得带水和相机。');
    await desktop().locator('#organize-apply').click();
    await desktop().locator('#toast').getByRole('button', { name: '撤销', exact: true }).click();
    await desktop().locator('#hide-note').click(); await page.locator('[data-notes-reopen-note]').click();
    assert.equal(await desktop().locator('#desktop-body').inputValue(), '去公园走走；记得带水和相机。');
    await page.locator('[data-notes-demo-reminder]').click();
    await desktop().getByRole('button', { name: '稍后10分钟', exact: true }).click();
    await page.locator('[data-notes-demo-reset]').click();
    await panel.locator('#hide-panel').click(); await page.locator('[data-notes-reopen-panel]').click();
    report.interactions.push('native notes cross-frame save, organize preview/apply/undo, close/reopen, reminder snooze, reset');
    await page.locator('#codex').scrollIntoViewIfNeeded();
    const quota = page.frameLocator('#codex iframe').frameLocator('#quota-frame');
    const detail = page.frameLocator('#codex iframe').frameLocator('#detail-frame');
    await detail.locator('.trend-chart').waitFor();
    await quota.locator('[data-action="opportunities"]').click(); await detail.locator('.opportunity-history > summary').click();
    assert.match(await detail.locator('.opportunity-history').innerText(), /已获得/);
    await quota.locator('[data-action="trend"]').click(); await detail.locator('[data-period="300"]').click();
    assert.match(await detail.locator('#details-content').innerText(), /82%/);
    report.interactions.push('native quota default trend, history and period switching');
    await page.locator('#appearance').scrollIntoViewIfNeeded();
    await page.locator('[data-ap-mode="accessible"]').click(); await page.locator('[data-ap-look="dark"]').click();
    const appearanceChat = page.frameLocator('[data-demo-appearance][data-demo="chat"]');
    await appearanceChat.locator('html[data-color-mode="accessible"]').waitFor();
    assert.equal(await appearanceChat.locator('html').getAttribute('data-accessible-appearance'), 'dark');
    assert.equal(await chat.locator('html').getAttribute('data-color-mode'), 'standard');
    report.interactions.push('latest real UI accessibility/theme controls remain independent from main demos');
    await page.reload();
    for (const [width, theme] of [[1440,'light'],[1440,'dark'],[390,'light'],[390,'dark'],[320,'light'],[320,'dark']]) {
      await page.setViewportSize({ width, height: width > 600 ? 1000 : 844 });
      await page.evaluate(theme => document.documentElement.dataset.theme = theme, theme);
      for (const id of ['top','codex','chat','customize','notes','appearance','download','install','updates']) {
        const section = page.locator(`#${id}`); await section.scrollIntoViewIfNeeded();
        await page.waitForTimeout(100);
        assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), `outer overflow ${width}/${theme}/${id}`);
        const overflow = await page.evaluate(() => [...document.querySelectorAll('iframe[data-app-demo]')].filter(f => f.contentDocument?.readyState === 'complete').flatMap(f => [f, ...f.contentDocument.querySelectorAll('iframe')]).filter(f => !f.hidden && f.contentWindow?.innerWidth > 0 && f.contentDocument?.documentElement.scrollWidth > f.contentWindow.innerWidth + 1).map(f => f.src));
        assert.deepEqual(overflow, [], `embedded overflow ${width}/${theme}/${id}`);
      }
      await page.evaluate(() => document.querySelectorAll('.site-header,.skip-link,[data-back-to-top]').forEach(e => e.style.setProperty('opacity', '0', 'important')));
      const ids = width === 1440 || (width === 390 && theme === 'light') ? ['top','codex','customize','notes','appearance','download','install'] : ['customize','notes'];
      for (const id of ids) await page.locator(`#${id}`).screenshot({ path: path.join(out, `${id}-${width}-${theme}.png`) });
      report.layouts.push({ width, theme, horizontalOverflow: false });
    }
    await page.emulateMedia({ reducedMotion: 'reduce', colorScheme: 'dark' });
    await page.evaluate(() => document.documentElement.removeAttribute('data-theme'));
    await page.locator('#chat').scrollIntoViewIfNeeded();
    await chat.locator('html[data-accessible-appearance="dark"]').waitFor();
    assert.equal(await chat.locator('#chat-avatar').getAttribute('data-avatar-active'), 'false');
    assert.equal(await page.locator('html').evaluate(e => getComputedStyle(e).getPropertyValue('--page').trim()), '#11151b');
    assert.deepEqual(errors, []); assert.deepEqual(failed, []);
    report.reducedMotion = 'passed'; report.systemDark = 'passed';
    fs.writeFileSync(path.join(out, 'browser-verification.json'), JSON.stringify(report, null, 2));
    console.log(JSON.stringify(report, null, 2));
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
