async page => {
  const failures = [], completed = [], requests = [];
  page.on('pageerror', error => failures.push(error.message));
  page.on('request', request => requests.push(request.url()));
  const check = (value, message) => { if (!value) throw Error(message); };
  await page.setViewportSize({ width: 1100, height: 850 });
  await page.goto('http://127.0.0.1:9062/__notes-check');
  const panel = page.frameLocator('[data-notes-frame="panel"]');
  const desktop = () => page.frameLocator('[data-notes-frame="desktop"]');
  await panel.locator('#panel').waitFor({ state: 'visible' });
  await desktop().locator('#desktop-note').waitFor({ state: 'visible' });
  check(await panel.locator('#search-row').isHidden(), 'Original compact search must start closed.');
  check(await panel.locator('#records .record-title').count() === 3, 'Three synthesized notes must render.');
  await panel.getByRole('button', { name: '取消收藏：周末的小计划', exact: true }).click();
  await panel.getByRole('button', { name: '收藏：周末的小计划', exact: true }).waitFor();
  await desktop().locator('#desktop-body').fill('去公园走走；记得带水和相机。');
  await panel.locator('.note-preview').filter({ hasText: '去公园走走；记得带水和相机。' }).waitFor();
  await desktop().locator('#desktop-more').click();
  await desktop().locator('#actions-list').getByRole('button', { name: '智能整理', exact: true }).click();
  await desktop().locator('#organize-generate').click();
  check(await desktop().locator('#desktop-body').inputValue() === '去公园走走；记得带水和相机。', 'Preview must preserve source.');
  await desktop().locator('#organize-apply').click();
  await page.waitForFunction(() => document.querySelector('[data-notes-frame="desktop"]').contentDocument?.querySelector('#desktop-body')?.value.includes('• '));
  check((await desktop().locator('#desktop-body').inputValue()).includes('• '), 'Confirm must apply the preview.');
  await desktop().locator('#toast').getByRole('button', { name: '撤销', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('[data-notes-frame="desktop"]').contentDocument?.querySelector('#desktop-body')?.value === '去公园走走；记得带水和相机。');
  check(await desktop().locator('#desktop-body').inputValue() === '去公园走走；记得带水和相机。', 'Undo must recover the source.');
  completed.push('favorite, cross-frame auto-save, native organizer preview/apply/undo');
  await panel.locator('#toggle-search').click(); await panel.locator('#search').fill('阅读');
  check(await panel.locator('#records .record-title').count() === 1, 'Search must filter records.');
  await panel.locator('#search').press('Escape');
  await panel.locator('#filter').click(); await panel.locator('#filter-menu').getByRole('button', { name: '管理分类', exact: true }).click();
  await panel.locator('#category-add').click(); await panel.locator('#new-category-name').fill('旅行'); await panel.locator('#new-category-save').click();
  await panel.locator('#category-list .category-name').filter({ hasText: '旅行' }).waitFor(); await panel.locator('#category-manager-done').click();
  await panel.locator('#new-button').click(); await panel.locator('#edit-note-title').fill('网页新便签'); await panel.locator('#edit-note-body').fill('示例行李清单');
  await panel.locator('#edit-note-category').selectOption({ label: '旅行' }); await panel.locator('#editor-save').click();
  await panel.getByRole('button', { name: '网页新便签，更多操作', exact: true }).click();
  await panel.locator('#actions-list').getByRole('button', { name: '在桌面显示', exact: true }).click();
  await desktop().locator('#desktop-title').waitFor();
  await page.waitForFunction(() => document.querySelector('[data-notes-frame="desktop"]').contentDocument?.querySelector('#desktop-title')?.value === '网页新便签');
  await desktop().locator('#hide-note').click(); await page.locator('[data-notes-reopen-note]').waitFor({ state: 'visible' });
  await page.locator('[data-notes-reopen-note]').click(); await desktop().locator('#desktop-note').waitFor({ state: 'visible' });
  check(await desktop().locator('#desktop-body').inputValue() === '示例行李清单', 'Closing/reopening must preserve the note.');
  await panel.getByRole('button', { name: '网页新便签，更多操作', exact: true }).click(); await panel.locator('#actions-list').getByRole('button', { name: '移到回收站', exact: true }).click();
  await panel.locator('#filter').click(); await panel.locator('#filter-menu').getByRole('button', { name: /回收站/ }).click();
  await panel.getByRole('button', { name: '网页新便签', exact: true }).click(); await panel.locator('#actions-list').getByRole('button', { name: '恢复到列表', exact: true }).click();
  await panel.locator('#filter').click(); await panel.locator('#filter-menu').getByRole('button', { name: /全部便签/ }).click();
  check(await panel.getByRole('button', { name: '网页新便签', exact: true }).count() === 1, 'Trash restore must recover the note.');
  completed.push('original search, category creation, note creation, close/reopen, trash/restore');
  await panel.locator('#todos-tab').click();
  await panel.getByRole('button', { name: '给自己留一点休息时间', exact: true }).click();
  const tomorrow = await page.evaluate(() => { const date = new Date(); date.setDate(date.getDate()+1); return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`; });
  await panel.locator('#edit-due').fill(tomorrow); await panel.locator('#edit-reminder-date').fill(tomorrow); await panel.locator('#edit-reminder-time').fill('10:30'); await panel.locator('#editor-save').click();
  await panel.locator('#filter').click(); await panel.locator('#filter-menu').getByRole('button', { name: /全部待办/ }).click();
  const rest = panel.locator('#records .record').filter({ has: panel.locator('.record-title').filter({ hasText: '给自己留一点休息时间' }) });
  check((await rest.innerText()).includes('10:30'), 'Configured reminder time must appear independently of due date.');
  await page.locator('[data-notes-demo-reminder]').click(); await desktop().locator('#reminder').waitFor({ state: 'visible' });
  await desktop().getByRole('button', { name: '稍后10分钟', exact: true }).click();
  await page.waitForFunction(() => { const frame=document.querySelector('[data-notes-frame="desktop"]'); return frame.hidden || !frame.src.includes('reminder.html'); });
  check((await rest.innerText()).includes('提醒：今天'), 'Snooze must change reminder while due remains tomorrow.');
  await rest.getByRole('button', { name: '完成：给自己留一点休息时间', exact: true }).click();
  await panel.getByRole('button', { name: '给自己留一点休息时间，更多操作', exact: true }).click(); await panel.locator('#actions-list').getByRole('button', { name: '归档已完成', exact: true }).click();
  await panel.locator('#filter').click(); await panel.locator('#filter-menu').getByRole('button', { name: /已归档/ }).click();
  await panel.getByRole('button', { name: '给自己留一点休息时间，更多操作', exact: true }).click(); await panel.locator('#actions-list').getByRole('button', { name: '恢复到已完成', exact: true }).click();
  await panel.locator('#filter').click(); await panel.locator('#filter-menu').getByRole('button', { name: /已完成/ }).click();
  check(await panel.getByRole('button', { name: '给自己留一点休息时间', exact: true }).count() === 1, 'Archive restore must preserve completion.');
  completed.push('independent dates/reminders, real reminder card/snooze, complete/archive/restore');
  await page.locator('[data-notes-demo-reset]').click(); await desktop().locator('#desktop-note').waitFor({ state: 'visible' });
  await page.evaluate(() => { for (const frame of document.querySelectorAll('iframe')) frame.contentWindow.postMessage({type:'qiuqiu-demo-theme',appearance:'dark',colorMode:'accessible'},location.origin); });
  await page.waitForFunction(() => Array.from(document.querySelectorAll('iframe')).every(frame=>frame.contentDocument?.documentElement.dataset.notesAppearance==='dark'&&frame.contentDocument?.documentElement.dataset.colorMode==='accessible'));
  await page.setViewportSize({ width: 320, height: 850 });
  const widths = await page.evaluate(() => ({ page: document.documentElement.scrollWidth, viewport: innerWidth, frames: Array.from(document.querySelectorAll('iframe')).map(frame=>({width:frame.contentWindow.innerWidth,scroll:frame.contentDocument.documentElement.scrollWidth})) }));
  check(widths.page <= widths.viewport && widths.frames.every(frame=>frame.scroll<=frame.width), '320px page and original frames must have no horizontal overflow.');
  await panel.locator('#hide-panel').click(); await page.locator('[data-notes-reopen-panel]').click(); check(await panel.locator('#panel').isVisible(), 'Main panel must reopen.');
  completed.push('theme message, dark/accessible original appearance, 320px unscaled responsive layout, panel close/reopen');
  check(!failures.length, JSON.stringify(failures)); check(requests.every(url=>url.startsWith('http://127.0.0.1:9062/')), 'No external requests allowed.');
  return { completed, widths, failures, externalRequests: 0 };
}
